//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UbiqSecurity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UbiqResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UbiqResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UbiqSecurity.UbiqResources", typeof(UbiqResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument, alphabet cannot be empty.
        /// </summary>
        internal static string InvalidAlphabetEmpty {
            get {
                return ResourceManager.GetString("InvalidAlphabetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalig argument, input character not found in alphabet.
        /// </summary>
        internal static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input length.
        /// </summary>
        internal static string InvalidInputLength {
            get {
                return ResourceManager.GetString("InvalidInputLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid radix.
        /// </summary>
        internal static string InvalidRadix {
            get {
                return ResourceManager.GetString("InvalidRadix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid source length.
        /// </summary>
        internal static string InvalidSourceLength {
            get {
                return ResourceManager.GetString("InvalidSourceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tweak.
        /// </summary>
        internal static string InvalidTweak {
            get {
                return ResourceManager.GetString("InvalidTweak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tweak length.
        /// </summary>
        internal static string InvalidTweakLength {
            get {
                return ResourceManager.GetString("InvalidTweakLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key size error.
        /// </summary>
        internal static string KeySize {
            get {
                return ResourceManager.GetString("KeySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String exceeds desired length.
        /// </summary>
        internal static string MaxStringLength {
            get {
                return ResourceManager.GetString("MaxStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum text length out of range.
        /// </summary>
        internal static string MinTextLengthRange {
            get {
                return ResourceManager.GetString("MinTextLengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array can not be null.
        /// </summary>
        internal static string NullArrayArgument {
            get {
                return ResourceManager.GetString("NullArrayArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radix value out of range.
        /// </summary>
        internal static string RadixOutofRange {
            get {
                return ResourceManager.GetString("RadixOutofRange", resourceCulture);
            }
        }
    }
}
